name: testing

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install       
      - name: testing
        run: npm test
      - name: test build health
        run: npm run build